### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by andycuccaro** [oormicreations/VSRender#1] opened 2020-05-09 04:00 UTC
Whenever I try the addon, the following error comes up: 
```
Traceback (most recent call last):
  File "/home/andres/.config/blender/2.82/scripts/addons/VSRender.py", line 257, in execute
    splitparts(vsrtool.vsr_parts, vsrtool)
  File "/home/andres/.config/blender/2.82/scripts/addons/VSRender.py", line 140, in splitparts
    temp = codecs.open(outpath + ranges[n] + ".sh", "w", "utf-8")
  File "/usr/lib64/python3.8/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '//render/1-4339.sh'

location: <unknown location>:-1
```
Do you have any idea what could be causing it? I'm using Fedora 32 (Xfce), in a computer with an i5 @ 3.100GHz (4 cores).

**Comment by oormicreations** [comment] 2020-05-09 05:10
Either the directory "render" does not exist or there are no write permissions to create the file there.
Try changing the output path to an existing directory (In Blender's output properties panel).

**Comment by andycuccaro** [comment] 2020-05-10 01:40
The directory definitely exists. Should I grant write permissions to the addon then? How do I do that? Just `chmod a+rwx /home/user/.config/blender/2.82/scripts/addons/VSRender.py` or something?

**Comment by oormicreations** [comment] 2020-05-10 02:48
I could replicate your error.
I get the error when I type `//render/ `in the Output box.
I do not get error when I pick the folder by clicking the folder icon.

The issue is that blender can understand //render/ notation but python cannot. So you will need to provide a full path there. Like this:
`/media/user/disk1/myproject/render/`

Let me know if this works.

**Comment by andycuccaro** [comment] 2020-05-10 04:49
Yes, that works and now the split button doesn't throw any error and creates the scripts. But clicking on Parallel Render doesn't do anything. It literally doesn't produce any message in the Info editor :(

**Comment by oormicreations** [comment] 2020-05-10 05:39
Well, if you are willing to troubleshoot further, try these:
1 - Start blender from system terminal. (Change to blender program directory and start by typing `./blender`). Now see if any message appears there.
2 - The addon prints some messages in python console. So open python console and check.
3 - Run the part scripts manually and see if they throw errors. (Change to render directory in terminal and start `./1-xxxx.sh`

**Comment by andycuccaro** [comment] 2020-05-10 15:36
Thanks! I didn't quite follow your instructions, but I found _a_ workaround. 

After doing point 1 of your instructions, the following message appeared in my terminal: `sh: gnome-terminal: command not found`. So, I guess the script is hardcoded to use gnome-terminal then. 

As for 2, the addon didn't print any message that I could see 🤷. 

Now, for 3, I went to the render directory and opened the terminal there and tried to render the scripts, which threw a `Permission denied` error, which got solved by changing permissions to the script with a `chmod a+x 1-xxxx.sh` command. 

I changed `gnome-terminal` into `xfce4-terminal`within the VSRender.py script, saved it, ran it and it worked! :D 

Since I don't know any python, I couldn't find a way to make the script work with whatever is the default terminal, but I guess that's possible, no?

**Comment by oormicreations** [comment] 2020-05-11 00:24
Awesome. Great troubleshooting.
I had written about these issues in the readme file on main page. Yes, the addon was developed for Linux Mint with gnome terminal and I expected people with other flavours of linux to edit the code.

But anyway, I will update the addon with an option to use xfce4-terminal and will also add chmod.

Since I do not have Fedora or other stuff, I will ask users to please test these versions. I guess there is a fork where more features and fixes are being added. Check the forks link.

Thanks for the feedback and patience. I will close this issue now. Update coming soon.

**Closed as completed by oormicreations** 2020-05-11 00:24 UTC
